# Site Settings
title: Charlie's Chocolate Factory
email: charlie.bea.utiful@gmail.com
description: Charlie's Life
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.charlie.kim" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Charlie
user_description: Charlie Kim
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: BEA-Utiful
twitter_username: BEA__Utiful

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
